import { ThemeType } from "../types";

export const themes: ThemeType[] = [
   {
      name: "Red",
      id: "red",
      type: "dark",
      side_bar_bg: "bg-[#391b1c]",
      content_text: "text-[#ca4954]",
      content_hover_text: "hover:text-[#ca4954]",
      content_bg: "bg-[#ca4954]  text-[#fff]",
      content_hover_bg: "hover:bg-[#ca4954] hover:text-[#fff] ",
      container: "bg-[#2e0f10]",
   },
   {
      name: "Deep blue",
      id: "deep_blue",
      type: "dark",
      side_bar_bg: "bg-[#1b2639]",
      content_text: "text-[#0c9e85]",
      content_hover_text: "hover:text-[#0c9e85]",
      content_bg: "bg-[#0c9e85]  text-[#fff]",
      content_hover_bg: "hover:bg-[#0c9e85] hover:text-[#fff] ",
      container: "bg-[#0f1a2e]",
   },
   {
      name: "Light green",
      id: "green_light",
      type: "light",
      side_bar_bg: "bg-[#dde5e5]",
      content_text: "text-[#198585]",
      content_hover_text: "hover:text-[#198585]",
      content_bg: "bg-[#198585] text-[#fff]",
      content_hover_bg: "hover:bg-[#198585] hover:text-[#fff]",
      container: "bg-[#ced9d9]",
   },
   {
      name: "Gray",
      id: "gray",
      type: "light",
      side_bar_bg: "bg-[#d9d7d4]",
      content_text: "text-[#644646]",
      content_hover_text: "hover:text-[#644646]",
      content_bg: "bg-[#644646]  text-[#fff]",
      content_hover_bg: "hover:bg-[#644646] hover:text-[#fff]",
      container: "bg-[#e5e3df]",
   },
   {
      name: "White",
      id: "white",
      type: "light",
      side_bar_bg: "bg-[#d9d7d4]",
      content_text: "text-[#644646]",
      content_hover_text: "hover:text-[#644646]",
      content_bg: "bg-[#644646]  text-[#fff]",
      content_hover_bg: "hover:bg-[#644646] hover:text-[#fff]",
      container: "bg-[#e5e3df]",
   },
];
